### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by madchap** [cvallance/mongo-k8s-sidecar#26]
Hello,

I am trying out this sidecar, which sounds like a dream :-) I am having issues, however. I am doing it with StatefulSet.

I am trying to run the sidecar with docker image mongo:2. My current environment is based on coreos-vagrant multi and some glusterFS for persistent storage.

Starting the sidecar container, I get this:
```
npm info it worked if it ends with ok
npm info using npm@4.1.2
npm info using node@v7.7.1
npm info lifecycle mongo-k8s-sidecar@0.1.0~prestart: mongo-k8s-sidecar@0.1.0
npm info lifecycle mongo-k8s-sidecar@0.1.0~start: mongo-k8s-sidecar@0.1.0

> mongo-k8s-sidecar@0.1.0 start /opt/cvallance/mongo-k8s-sidecar
> forever src/index.js

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting up mongo-k8s-sidecar
Error in workloop { [Error: Unauthorized
] message: 'Unauthorized\n', statusCode: 401 }
Error in workloop { MongoError: can't get local.system.replset config from self or any seed (EMPTYCONFIG)
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
  name: 'MongoError',
  message: 'can\'t get local.system.replset config from self or any seed (EMPTYCONFIG)',
  startupStatus: 3,
  info: 'run rs.initiate(...) if not yet done for the set',
  ok: 0,
  errmsg: 'can\'t get local.system.replset config from self or any seed (EMPTYCONFIG)' }
```

If i kubectl exec into one of the mongo container and initiate the replicaSet myself:
```
> rs.initiate()
{
        "info2" : "no configuration explicitly specified -- making one",
        "me" : "mongo-0:27017",
        "info" : "Config now saved locally.  Should come online in about a minute.",
        "ok" : 1
}
```

which then triggers the following log in the sidecar:
```
Addresses to add:    [ '10.2.19.8:27017', '10.2.93.8:27017', '10.2.63.9:27017' ]
Addresses to remove: []
Error in workloop { [Error: Unauthorized
] message: 'Unauthorized\n', statusCode: 401 }
Error in workloop { MongoError: no such cmd: replSetGetConfig
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
  name: 'MongoError',
  message: 'no such cmd: replSetGetConfig',
  ok: 0,
  errmsg: 'no such cmd: replSetGetConfig',
  code: 59,
  'bad cmd': { replSetGetConfig: 1 } }
```

I am currently investigating, yet I very much welcome pointers if you have any.

I will post here any findings (and possible mistakes) I find.

Thank you!
fred

**Comment by madchap** [comment]
hehe.. it helps me to write things out.

I meant to be using mongo:3 and not mongo:2. Works much better now :)

Thanks!
fred
