### ISSUE TITLE
Replica member coup when Set ID is lost

### ISSUE THREAD

**Issue by henhouse** [cvallance/mongo-k8s-sidecar#27]
I am not sure how to reproduce this, but this was a result of scaling mongo up and down multiple times via the `kubectl scale --replicas=X statefulset mongo` command.

I was running tests and noticed performance went out the window until I checked the pod logs to find the logs being absolutely flooded with these messages (hundreds, potentially more _per second_, per pod).

`2017-03-28T12:09:44.891097041Z 2017-03-28T12:09:44.874+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 172.17.0.18:27017; InvalidReplicaSetConfig: replica set IDs do not match, ours: 58d8c51ad5bb19757ac841d2; remote node's: 58da2c6a046a5427009f1336`

This results in the pods staging repeated coups and electing themselves new masters constantly. I can see from my connections the masters cycle through all of the mongo pods running (I am running 4 currently) and switches shortly after.

If it somehow helps, I attach the sidecar output from mongo-0 below. I am honestly not sure if this is an issue with the sidecar, or even preventable. I just was mainly posting here to see if anyone has noticed this before as a result of continuous scaling up and down during testing phases.

> 2017-03-28T12:18:07.541385644Z        tags: {},
2017-03-28T12:18:07.541388008Z        slaveDelay: 0,
2017-03-28T12:18:07.541390261Z        votes: 1 },
2017-03-28T12:18:07.541392746Z      { _id: 19,
2017-03-28T12:18:07.541395025Z        host: '172.17.0.18:27017',
2017-03-28T12:18:07.541397295Z        arbiterOnly: false,
2017-03-28T12:18:07.541399560Z        buildIndexes: true,
2017-03-28T12:18:07.541401820Z        hidden: false,
2017-03-28T12:18:07.541404048Z        priority: 1,
2017-03-28T12:18:07.541406223Z        tags: {},
2017-03-28T12:18:07.541408426Z        slaveDelay: 0,
2017-03-28T12:18:07.541410585Z        votes: 1 },
2017-03-28T12:18:07.541412839Z      { _id: 20, host: '172.17.0.6:27017' },
2017-03-28T12:18:07.541415202Z      { _id: 21, host: '172.17.0.7:27017' } ],
2017-03-28T12:18:07.541417480Z   settings: 
2017-03-28T12:18:07.541419689Z    { chainingAllowed: true,
2017-03-28T12:18:07.541421902Z      heartbeatIntervalMillis: 2000,
2017-03-28T12:18:07.541424141Z      heartbeatTimeoutSecs: 10,
2017-03-28T12:18:07.541426397Z      electionTimeoutMillis: 10000,
2017-03-28T12:18:07.541428688Z      catchUpTimeoutMillis: 2000,
2017-03-28T12:18:07.541430923Z      getLastErrorModes: {},
2017-03-28T12:18:07.541433482Z      getLastErrorDefaults: { w: 1, wtimeout: 0 },
2017-03-28T12:18:07.541435856Z      replicaSetId: 58da2c6a046a5427009f1336 } }
2017-03-28T12:18:07.556109862Z Error in workloop { MongoError: Our replica set ID of 58da2c6a046a5427009f1336 did not match that of 172.17.0.6:27017, which is 58d8c51ad5bb19757ac841d2
2017-03-28T12:18:07.556134171Z     at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
2017-03-28T12:18:07.556140132Z     at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:483:72
2017-03-28T12:18:07.556144641Z     at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:429:16)
2017-03-28T12:18:07.556149183Z     at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:463:5)
2017-03-28T12:18:07.556153798Z     at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:319:22)
2017-03-28T12:18:07.556159526Z     at emitOne (events.js:96:13)
2017-03-28T12:18:07.556163791Z     at Socket.emit (events.js:191:7)
2017-03-28T12:18:07.556179163Z     at readableAddChunk (_stream_readable.js:176:18)
2017-03-28T12:18:07.556183624Z     at Socket.Readable.push (_stream_readable.js:134:10)
2017-03-28T12:18:07.556187840Z     at TCP.onread (net.js:554:20)
2017-03-28T12:18:07.556192136Z   name: 'MongoError',
2017-03-28T12:18:07.556196928Z   message: 'Our replica set ID of 58da2c6a046a5427009f1336 did not match that of 172.17.0.6:27017, which is 58d8c51ad5bb19757ac841d2',
2017-03-28T12:18:07.556201988Z   ok: 0,
2017-03-28T12:18:07.556206224Z   errmsg: 'Our replica set ID of 58da2c6a046a5427009f1336 did not match that of 172.17.0.6:27017, which is 58d8c51ad5bb19757ac841d2',
2017-03-28T12:18:07.556210736Z   code: 103,
2017-03-28T12:18:07.556214806Z   codeName: 'NewReplicaSetConfigurationIncompatible' }

**Comment by nearwood** [comment]
I'm having the same issue trying to scale a Mongo replica set via Docker SWARM. I believe it to be that on service restarts, IPs sometimes shuffle and each node cannot then find the other nodes and default to replicasets of one, with 127.0.0.1. This causes my initialization script to call rs.inititalize() on each node, which then breaks everything like the above.

**Comment by cvallance** [comment]
Looks like the `invalidReplicaSet` doesn't do any election process so everyone may start trying to init the replica set again. I'll create a PR to fix this.

**Comment by cvallance** [comment]
Added some code in https://github.com/cvallance/mongo-k8s-sidecar/pull/62 which should help with this scenario.

**Comment by marioeu** [comment]
Hi cvallance,

I'm still expiriencing this issue. Seems that this fix did not work.
Are you able to advise what more can be done?
I'm trying to find some way to remove the old  replica set IDs in runtime without have to manually remove data from node, but no lucky until now.

Any ideas would be great.
