### ISSUE TITLE
Master without slaves

### ISSUE THREAD

**Issue by felixPG** [cvallance/mongo-k8s-sidecar#53]
Hi:

Deploying mongo replset with side-car rise up to me the following problem:

Master are configured properly but sidecar cant add slave nodes because a **NewReplicaSetConfigurationIncompatible** error. Master work fine, I can insert and read data but of course, I cant read this data from the slave nodes because they dont appear in the replset configuration as slave. 

Below the logs from sidecar pod and mongo nodes.

**sidecar logs:**

```
Error in workloop { MongoError: The hosts mongo-0:27017 and 10.36.0.4:27017 all map to this node in new configuration version 2 for replica set rs0
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'MongoError',
  message: 'The hosts mongo-0:27017 and 10.36.0.4:27017 all map to this node in new configuration version 2 for replica set rs0',
  ok: 0,
  errmsg: 'The hosts mongo-0:27017 and 10.36.0.4:27017 all map to this node in new configuration version 2 for replica set rs0',
  code: 103,
  codeName: 'NewReplicaSetConfigurationIncompatible' }
```
Status of 3 mongo instance:
```
root@s-smartc2-zprei:/opt/kubernetes/mongodb# for i in `seq 0 2`; do kubectl exec mongo-$i -- sh -c '/usr/bin/mongo --eval="printjson(rs.isMaster())"'; done
Defaulting container name to mongo.
Use 'kubectl describe pod/mongo-0' to see all of the containers in this pod.
MongoDB shell version v3.4.8
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.8
{
        "hosts" : [
                "mongo-0:27017"
        ],
        "setName" : "rs0",
        "setVersion" : 1,
        "ismaster" : true,
        "secondary" : false,
        "primary" : "mongo-0:27017",
        "me" : "mongo-0:27017",
        "electionId" : ObjectId("59b283bd98a268a30af4eeb3"),
        "lastWrite" : {
                "opTime" : {
                        "ts" : Timestamp(1504872388, 1),
                        "t" : NumberLong(-1)
                },
                "lastWriteDate" : ISODate("2017-09-08T12:06:28Z")
        },
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2017-09-08T12:06:36.437Z"),
        "maxWireVersion" : 5,
        "minWireVersion" : 0,
        "readOnly" : false,
        "ok" : 1
}
Defaulting container name to mongo.
Use 'kubectl describe pod/mongo-1' to see all of the containers in this pod.
MongoDB shell version v3.4.8
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.8
{
        "ismaster" : **false**,
        "secondary" : **false**,
        "info" : "**Does not have a valid replica set config**",
        "isreplicaset" : true,
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2017-09-08T12:06:33.620Z"),
        "maxWireVersion" : 5,
        "minWireVersion" : 0,
        "readOnly" : false,
        "ok" : 1
}
Defaulting container name to mongo.
Use 'kubectl describe pod/mongo-2' to see all of the containers in this pod.
MongoDB shell version v3.4.8
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.8
{
        "ismaster" : **false**,
        "secondary" : **false**,
        "info" : "**Does not have a valid replica set config**",
        "isreplicaset" : true,
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2017-09-08T12:06:37.636Z"),
        "maxWireVersion" : 5,
        "minWireVersion" : 0,
        "readOnly" : false,
        "ok" : 1
}
root@s-smartc2-zprei:/opt/kubernetes/mongodb#
```
Logs for Members that dont have master or slave state:
```
> rs.status()
{
        "info" : "run rs.initiate(...) if not yet done for the set",
        "ok" : 0,
        "errmsg" : "**no replset config has been received**",
        "code" : 94,
        "codeName" : "**NotYetInitialized**"
}
>

**Comment by felixPG** [comment]
@cvallance an update for this please?, problem are related with **replSetReconfig got DuplicateKey**:
```
 [conn51] replSetReconfig got DuplicateKey: The hosts mongo-0:27017 and 10.36.0.4:27017 all map to this node in new configuration version 2 for replica set rs0 while validating { _id: "rs0", version: 2, members: [ { _id: 0, host: "mongo-0:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "10.36.0.4:27017" }, { _id: 2, host: "10.44.0.2:27017" } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 } } }
```
Regards

**Comment by RiaanLab** [comment]
I have created a work around, albeit a bit manual for now, to get anyone with a replicaset with issues synced again. You can run the following on one of your kubernetes nodes. (Change the namespace that your mongo RS is running in.)

NAMESPACE=infra-dev ; for MONGO_NODE in $(kubectl get pods --namespace="$NAMESPACE" --no-headers | grep mongo | awk '{ print $1 }'); do kubectl exec "$MONGO_NODE"  --namespace="$NAMESPACE" -- /bin/bash -c '/usr/bin/mongo --eval="printjson(rs.initiate())"'; done

Once you have run the above command you can check the RS status with:
 NAMESPACE=infra-dev ; for MONGO_NODE in $(kubectl get pods --namespace="$NAMESPACE" --no-headers | grep mongo | awk '{ print $1 }'); do kubectl exec "$MONGO_NODE"  --namespace="$NAMESPACE" -- /bin/bash -c '/usr/bin/mongo --eval="printjson(rs.status())"'; done

You should see something like this is the RS is working as planned.
Defaulting container name to mongo.
Use 'kubectl describe pod/mongo-rs0-4' to see all of the containers in this pod.
MongoDB shell version v3.4.9
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.9
{
	"set" : "rs0",
	"date" : ISODate("2017-10-19T06:30:12.522Z"),
	"myState" : 2,
	"term" : NumberLong(16),
	"syncingTo" : "mongo-rs0-3.mongo-rs0.infra-dev.svc.cluster.local:27017",
	"heartbeatIntervalMillis" : NumberLong(2000),
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1508394600, 1),
			"t" : NumberLong(16)
		},
		"appliedOpTime" : {
			"ts" : Timestamp(1508394610, 1),
			"t" : NumberLong(16)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1508394610, 1),
			"t" : NumberLong(16)
		}
	},
	"members" : [
		{
			"_id" : 8,
			"name" : "mongo-rs0-0.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 51,
			"optime" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDate" : ISODate("2017-10-19T06:30:10Z"),
			"optimeDurableDate" : ISODate("2017-10-19T06:30:10Z"),
			"lastHeartbeat" : ISODate("2017-10-19T06:30:10.533Z"),
			"lastHeartbeatRecv" : ISODate("2017-10-19T06:30:11.525Z"),
			"pingMs" : NumberLong(0),
			"electionTime" : Timestamp(1508334217, 1),
			"electionDate" : ISODate("2017-10-18T13:43:37Z"),
			"configVersion" : 352401
		},
		{
			"_id" : 9,
			"name" : "mongo-rs0-1.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 51,
			"optime" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDate" : ISODate("2017-10-19T06:30:10Z"),
			"optimeDurableDate" : ISODate("2017-10-19T06:30:10Z"),
			"lastHeartbeat" : ISODate("2017-10-19T06:30:10.533Z"),
			"lastHeartbeatRecv" : ISODate("2017-10-19T06:30:12.517Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "mongo-rs0-0.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"configVersion" : 352401
		},
		{
			"_id" : 10,
			"name" : "mongo-rs0-2.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 51,
			"optime" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDate" : ISODate("2017-10-19T06:30:10Z"),
			"optimeDurableDate" : ISODate("2017-10-19T06:30:10Z"),
			"lastHeartbeat" : ISODate("2017-10-19T06:30:10.533Z"),
			"lastHeartbeatRecv" : ISODate("2017-10-19T06:30:10.522Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "mongo-rs0-0.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"configVersion" : 352401
		},
		{
			"_id" : 11,
			"name" : "mongo-rs0-3.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 51,
			"optime" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDate" : ISODate("2017-10-19T06:30:10Z"),
			"optimeDurableDate" : ISODate("2017-10-19T06:30:10Z"),
			"lastHeartbeat" : ISODate("2017-10-19T06:30:10.533Z"),
			"lastHeartbeatRecv" : ISODate("2017-10-19T06:30:10.522Z"),
			"pingMs" : NumberLong(0),
			"syncingTo" : "mongo-rs0-0.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"configVersion" : 352401
		},
		{
			"_id" : 12,
			"name" : "mongo-rs0-4.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 70,
			"optime" : {
				"ts" : Timestamp(1508394610, 1),
				"t" : NumberLong(16)
			},
			"optimeDate" : ISODate("2017-10-19T06:30:10Z"),
			"syncingTo" : "mongo-rs0-3.mongo-rs0.infra-dev.svc.cluster.local:27017",
			"configVersion" : 352401,
			"self" : true
		}
	],
	"ok" : 1
}

**Comment by cvallance** [comment]
@felixPG - how did the replica set initialize itself? The first one that comes up should initialize with an IP addres and not `mongo-0:27017`.

**Comment by AntoninBeaufort** [comment]
Same problem

**Comment by smyth64** [comment]
same problem =/

It's really annoying because that's used in an official tutorial from google

**Comment by AntoninBeaufort** [comment]
This is a problem of permissions for the sidecar, all we have to do is create a file with this content : 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
And do a `kubectl apply -f filename.yaml`

**Comment by felixPG** [comment]
@AntoninBeaufort by default all pods run with the default service account, is not mandatory apply your clusterrolebinding.

**Comment by jasonquick** [comment]
This solved the problem for me. Thanks @AntoninBeaufort.

> This is a problem of permissions for the sidecar, all we have to do is create a file with this content :
> 
> ```
> apiVersion: rbac.authorization.k8s.io/v1beta1
> kind: ClusterRoleBinding
> metadata:
>   name: default-view
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: view
> subjects:
>   - kind: ServiceAccount
>     name: default
>     namespace: default
> ```
> 
> And do a `kubectl apply -f filename.yaml`

**Comment by majest** [comment]
The error occurs because side car tries to add the ip address and the domain name is already there. Adding KUBERNETES_MONGO_SERVICE_NAME env variable to the sidecar solved the problem for me. The value should be the name of the service. 

```            - name: KUBERNETES_MONGO_SERVICE_NAME 
              value: "mongo" ```
