### ISSUE TITLE
Istio issues with TLS

### ISSUE THREAD

**Issue by galo** [cvallance/mongo-k8s-sidecar#55]
I've been deploying Mongo with the side-car using StatefullSets and Istio.io. It works well, still there is an issue with istio-auth which forces TLS between pods, reported this in the Istio Users group [1]

TLS should be handled by Istio Envoy, but somehow the sidecar complains about SSL issues connecting to the other pods. I'll take a close look at this, but let me know if somebody already noticed.

[1] https://groups.google.com/forum/#!topic/istio-users/5fO83wx2H1M

Logs 
Error in workloop { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }

**Comment by cvallance** [comment]
Hi @galo - I see from the google group link you posted that Istio is working on a fix for headless services... do you know if its been fixed? I'm going to close this issue but feel free to update with a comment once they have fixed it. Cheers.

**Comment by adityakar** [comment]
Was there a resolution this issue?
