### ISSUE TITLE
mongo sidecar container does not attempt SSL connection with SSL enabled

### ISSUE THREAD

**Issue by phthano** [cvallance/mongo-k8s-sidecar#76]
I am having an issue with this which may be obvious to the designer but is not to me. I stepped through all the documentation and I am unable to get the sidecar to establish an ssl connection to my container. 
It appears to be trying to connect to localhost but I think that is because it's an initial failure of ssl. I have the correct podname specified in the db string and it even shows so. Any insight would be appreciated.
```

Initializing node with hostname podname-mongo-0
Options are {"mongoOptions":{"ssl":true,"sslAllowInvalidCertificates":true,"sslAllowInvalidHostnames":true}}
Error in workloop { MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at Pool.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:189:7)
    at Connection.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:192:7)
    at TLSSocket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:291:19)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:189:7)
  name: 'MongoError',
  message: 'failed to connect to server [127.0.0.1:27017] on first connect' }

```

**Comment by phthano** [comment]
This was related to an expired (not invalid) SSL certificate in an old repository
