### ISSUE TITLE
Simple Authentication always fails 

### ISSUE THREAD

**Issue by cescoferraro** [cvallance/mongo-k8s-sidecar#82]
I am running kops on AWS. I can get the mongo  cluster to work without authentication, but as soon as I try to secure it with simple user/password the nodes fail to connect.

I am creating the user like
`db.createUser( { user: "cesco", pwd: "mypassword", roles::[{role:"root", db:"admin"}] })`
then deleting the statefulset and creating back again uncommenting the below commented lines

```
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: development
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo:3.6
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
            # - "--auth"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongodb-service"
            # - name: MONGODB_USERNAME
            #   value: "cesco"
            # - name: MONGODB_PASSWORD
            #   value: "mypassword"
            # - name: MONGODB_DATABASE
            #   value: "admin"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
```

On the sidecar-log i get
```
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Error in workloop { MongoError: Authentication failed.
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:333:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1525288116 },
  '$clusterTime': 
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1525288116 },
     signature: { hash: [Binary], keyId: [Long] } } }
```

I can exec into the mongod-0 pod and run `mongo -u cesco -p mypassword` and log in just right.As well as running `use admin` `db.auth("cesco","mypassord")` I get 1

Logs show 

```
2018-05-02T19:13:22.851+0000 I ACCESS   [conn12] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-2.mongodb-service.default.svc.cluster.local:27017", fromId: 2, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.039+0000 I REPL_HB  [replexec-0] Error in heartbeat (requestId: 817) to mongod-2.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.063+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:54200 #13 (11 connections now open)
2018-05-02T19:13:23.063+0000 I NETWORK  [conn13] received client metadata from 127.0.0.1:54200 conn13: { driver: { name: "nodejs", version: "2.2.35" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.115-k8s" }, platform: "Node.js v9.8.0, LE, mongodb-core: 2.1.19" }
2018-05-02T19:13:23.064+0000 I ACCESS   [conn13] SCRAM-SHA-1 authentication failed for cesco on admin from client 127.0.0.1:54200 ; UserNotFound: Could not find user cesco@admin
2018-05-02T19:13:23.122+0000 I REPL_HB  [replexec-2] Error in heartbeat (requestId: 819) to mongod-1.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.191+0000 I ACCESS   [conn6] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-1.mongodb-service.default.svc.cluster.local:27017", fromId: 1, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.352+0000 I ACCESS   [conn12] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-2.mongodb-service.default.svc.cluster.local:27017", fromId: 2, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.539+0000 I REPL_HB  [replexec-1] Error in heartbeat (requestId: 821) to mongod-2.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.623+0000 I REPL_HB  [replexec-0] Error in heartbeat (requestId: 823) to mongod-1.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.692+0000 I ACCESS   [conn6] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-1.mongodb-service.default.svc.cluster.local:27017", fromId: 1, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:23.852+0000 I ACCESS   [conn12] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-2.mongodb-service.default.svc.cluster.local:27017", fromId: 2, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.040+0000 I REPL_HB  [replexec-2] Error in heartbeat (requestId: 825) to mongod-2.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.124+0000 I REPL_HB  [replexec-1] Error in heartbeat (requestId: 827) to mongod-1.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.193+0000 I ACCESS   [conn6] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-1.mongodb-service.default.svc.cluster.local:27017", fromId: 1, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.353+0000 I ACCESS   [conn12] Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-2.mongodb-service.default.svc.cluster.local:27017", fromId: 2, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.541+0000 I REPL_HB  [replexec-0] Error in heartbeat (requestId: 829) to mongod-2.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
2018-05-02T19:13:24.625+0000 I REPL_HB  [replexec-2] Error in heartbeat (requestId: 831) to mongod-1.mongodb-service.default.svc.cluster.local:27017, response status: Unauthorized: not authorized on admin to execute command { replSetHeartbeat: "rs0", configVersion: 5, hbv: 1, from: "mongod-0.mongodb-service.default.svc.cluster.local:27017", fromId: 0, term: 1, $replData: 1, $clusterTime: { clusterTime: Timestamp(1525288116, 1), signature: { hash: BinData(0, 259E9B3067A93809C76C1DC5B31CA15C0B2814DF), keyId: 6551044020938735618 } }, $db: "admin" }
```
 

What I am doing wrong? I need to grant external access to this database, otherwise i would not care about authentication. Help would be very much appreciated

**Comment by cescoferraro** [comment]
Strange thing I notice is that if I enable auth on the sidecar and not on mongod, the replicas are able to connect, but the logs get full of 

```
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
```
As soon as I enable `--auth` flag on the mongod I replicas fail to connect to master

**Comment by cescoferraro** [comment]
Finally got it to work with https://gist.github.com/thilinapiy/0c5abc2c0c28efe1bbe2165b0d8dc115
Only thing I change is the password and the replica count. I using 3 without any issues.

I just cannot realize why it does not work the way I was doing. Enabling with after setting a sido user seems to be the mongo way to do this 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by supereagle** [comment]
> Strange thing I notice is that if I enable auth on the sidecar and not on mongod, the replicas are able to connect,

@cescoferraro  I meet the same problem, how do you enable auth on the sidecar?

**Comment by supereagle** [comment]
Maybe it is caused by the bug https://jira.mongodb.org/browse/SERVER-31916, my MongoDB is 3.6.4.

**Comment by cescoferraro** [comment]
The gist on my last comment works just fine. I cannot find the reason why

**Comment by fairlight12** [comment]
Replica sets and sharded clusters require internal authentication between members when access control is enabled. For more details, please see Internal Authentication.
